### ISSUE TITLE
How to config urls?

### ISSUE THREAD

**Issue by gasse** [web-arena-x/webarena#1]
Hi, I'm trying to experiment with webarena locally. Which urls am I supposed to use in the config file?

https://github.com/web-arena-x/webarena/blob/b454f2dcfdc62af07beebb832b04bf8991ca409f/README.md?plain=1#L31

**Comment by ltzheng** [comment]
Experiencing the same issue, any possible solutions? Thanks!

**Comment by DavidPetrus** [comment]
You can copy the URLs from the URL_MAPPINGS dictionary in line 31.

**Comment by optimass** [comment]
Great!
The minimal example worked.
The command to launch GPT3 on a task in the README failed however.
I created a PR to fix it: https://github.com/web-arena-x/webarena/pull/2

**Comment by jianghoy** [comment]
@shuyanzhou I saw you added the script with link to some ec2, is that the benchmarking website?

**Comment by shuyanzhou** [comment]
Hi @jianghoy, the websites hosted on AWS are only for **demo** purposes. We are working on finalizing the docker images. You will be able to host your own websites to ensure the reproducibilities.

**Comment by davidbau** [comment]
Will source code for the stubbed websites also be released?

**Comment by shuyanzhou** [comment]
@davidbau Yes, we just released the instructions on how to self-host all websites in WebArena. Check out [this README](https://github.com/web-arena-x/webarena/blob/main/environment_docker/README.md)
