### ISSUE TITLE
No way to aggregate customers by order count when limited to status

### ISSUE THREAD

**Issue by moladeyal** [web-arena-x/webarena#101]
Several tasks (ids 288,292, 62, 64, 65) require to get the top k customers by the order count with status=x (e.g. status=completed, status=cancelled).
I could not find such an option in the UI. Nor did I find a successful user trajectory from those which were published.

What is the expected way to complete those tasks? 

Thanks,
Eyal

**Comment by moladeyal** [comment]
(Probably also relevant to task ids 289-291)

**Comment by shuyanzhou** [comment]
You are right; there is no option to gather customers by the number of orders. These tasks require the agent to understand the tables. The humans also perform literal counting of orders per user, so there is no recording of the counting.
