### ISSUE TITLE
Unable to click an external link that jumps to a new page 

### ISSUE THREAD

**Issue by ryoungj** [web-arena-x/webarena#102]
Hi Shuyan,

Thanks for creating and sharing this amazing environment! 

I've observed that the external link (that jumps to a new page) cannot be accessed via the 'click' action. An example is clicking the 'slack' at the bottom of this [website](https://arxiv.org/list/hep-lat/2001) is not effective in webarena.

It'd be great to fix it, but it is not a big issue anyways!

**Comment by shuyanzhou** [comment]
The fix has been applied to the merge repo of WebArena and VisualWebArena
