### ISSUE TITLE
Postmill rate limit.

### ISSUE THREAD

**Issue by afourney** [web-arena-x/webarena#120]
We're hitting a rate limit when testing the Postmill/reddit questions. Is there a way to disable this?

![image](https://github.com/web-arena-x/webarena/assets/4017093/442da1c5-0470-4645-ade4-39343ba214b9)

**Comment by shuyanzhou** [comment]
@robert1003 can you explain how to reset the rate limit for trust users?

cc. @frankxu2004

**Comment by frankxu2004** [comment]
As for resetting the rate limit, I think the simplest way is to reset the whole docker container with the provided image, and apply the above fix.

**Comment by frankxu2004** [comment]
Actually to kill the rate limit completely, there's a hack. We left the website mostly as-is for it to mimic real websites as much as possible (e.g. real websites usually have anti-spam or anti-bot mechanism).

Nonetheless, if you think this is too much of a hassle, then:

**Comment by afourney** [comment]
Fantastic. Thanks!
