### ISSUE TITLE
Unstablility of gitlab website

### ISSUE THREAD

**Issue by taogoddd** [web-arena-x/webarena#122]
Dear Authors,

I deployed the Gitlab website locally, but I found that it is unstable, e.g., if I keep visiting it, sometimes it works normally, while sometimes it reports 502. Any possible reason and solution for this? 

Thanks!

**Comment by frankxu2004** [comment]
You could check the server load (CPU, RAM) to see if it's overloaded while 502. The Gitlab is quite resource hungry so it might be best to have a big beefy server.
