### ISSUE TITLE
Environments are 300GB+

### ISSUE THREAD

**Issue by devinat1** [web-arena-x/webarena#128]
I am wondering why the docker tar files are so large. I am trying to reproduce the environment locally to avoid paying the EC2 pricing.

**Comment by shuyanzhou** [comment]
The main storage comes from the *data*, such as the product image, description, gitlab repo etc.

**Comment by Hodge931** [comment]
How do we reproduce the environments locally? Thanks a lot!

**Comment by shuyanzhou** [comment]
@Hodge931 What do you mean by reproducing the environment?

**Comment by Hodge931** [comment]
I mean, setting up environments without using the amazon AMI image.

**Comment by shuyanzhou** [comment]
You can check out [this section](https://github.com/web-arena-x/webarena/tree/main/environment_docker#individual-website) to download dockers and setup individual websites
