### ISSUE TITLE
Can't access websites on AWS instance

### ISSUE THREAD

**Issue by ScottLinnn** [web-arena-x/webarena#130]
I followed the instruction [here](https://github.com/web-arena-x/webarena/blob/main/environment_docker/README.md) to run docker on the AMI. After I completed all the commands before "You should be able to access your environment websites now, and stop reading. However, if you are unable to use AWS AMI, read below to set up on your own machine.", I can't access the websites. 

![image](https://github.com/web-arena-x/webarena/assets/86640627/33f6b8fb-1440-401b-8707-f09097cf05b1)

**Comment by frankxu2004** [comment]
Can you check if the instance now allows for inbound traffic in the firewall setting?  https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/authorizing-access-to-an-instance.html . Also you could try `curl localhost:7770` inside the ec2 machine to check if the websites are up and running

**Comment by ScottLinnn** [comment]
I fixed this, thanks!
