### ISSUE TITLE
location of dockerfile for images

### ISSUE THREAD

**Issue by lalo** [web-arena-x/webarena#140]
Hi - where are the dockerfiles for the images located? is there any plan to contribute them back to the open source community? It would be interesting to split the images with the runtime backend code vs the static content (db/images/posts/etc).

**Comment by frankxu2004** [comment]
Unfortunately we didn't use Dockerfiles for the creation of these docker images. 

For php-based websites, we started with https://github.com/adhocore/docker-lemp container, and installed Magento in it for the web shopping websites, and Postmill in it for the reddit website. For the gitlab one we adapted from the official gitlab-ce docker image. We then import all the data into these websites and finally docker export to generate a full image export.

As for the backend code vs static content, the backend code are not created by us, but rather existing open-source projects for these websites.

Shopping: Adobe Magento Community 
Forum: Postmill
GitLab: just gitlab community version
Map: openstreetmap

So most of the stuff in our docker images are mainly the static content.
We might consider create recipes for how to decouple these things.
Hope it helps!
