### ISSUE TITLE
Wikipedia website setup

### ISSUE THREAD

**Issue by gasse** [web-arena-x/webarena#144]
HI, I am trying to setup WebArena on an Azure VM. I am unsure what I should use here for `<your-path-to-downloaded-folder>`
https://github.com/web-arena-x/webarena/blob/de524be99e5369e234d91f1e52c0d46dec360e00/environment_docker/README.md?plain=1#L156

Thanks!

**Comment by frankxu2004** [comment]
Sorry about the confusion.

The <your-path-to-downloaded-folder> should be the path to the directory that holds the .zim file that you downloaded
