### ISSUE TITLE
Connection Refused on AWS hosted sites

### ISSUE THREAD

**Issue by peterychang** [web-arena-x/webarena#147]
I'm currently getting connection refused errors on the AWS hosted sites; we're specifically using the maps and wiki images for our tests, but it appears that all of the hosted images are currently down

> playwright._impl._errors.Error: Page.goto: net::ERR_CONNECTION_REFUSED at http://ec2-3-131-244-37.us-east2.compute.amazonaws.com:3000/

Manually visiting the sites via browser also fails to load with a CONNECTION_TIMED_OUT

It appears to have been working earlier today.

**Comment by idanshen** [comment]
Same here. My AWS hosted sites are not working. I can still SSH into the server but the websites themselves are not responding.

Rebooting or even starting a new instance doesn't seem to work

**Comment by LapshinA** [comment]
+1

**Comment by plzdoo** [comment]
+1

**Comment by afourney** [comment]
+1

**Comment by dgjun32** [comment]
+1

**Comment by frankxu2004** [comment]
It should be http://ec2-3-131-244-37.us-east-2.compute.amazonaws.com:3000

Alternatively you could try this to setup your own instance with the AWS AMI method: https://github.com/web-arena-x/webarena/blob/main/environment_docker/README.md#pre-installed-amazon-machine-image 

After running the commands, the map should be also accessible from your own AWS EC2 URL:3000
