### ISSUE TITLE
Docker loading forever on Mac

### ISSUE THREAD

**Issue by lyneyandlynette** [web-arena-x/webarena#15]
Hi, 
Did anyone successfully building the codebase on Mac?
I'm trying to `docker load` the webpages on Mac, however
for my MacBook with intel, docker load command **takes forever**;
for my MacBook with M1X chip, it can load the 9G website, but for larger ones, it keeps getting "`unexpected EOF`" error.
Does anyone know how to deal with this? Thank you!

**Comment by lyneyandlynette** [comment]
@kohjingyu Hi, thank you for the reply! May I know if you set 160GB to load all the webpages at once? As the file sizes add to up to more than 160GB, how do you get the number then? Thank you!

**Comment by shuyanzhou** [comment]
160GB for the *shopping* site only. @frankxu2004 do you thoughts on an estimation on the Docker virtual disk limit?

**Comment by RogerChern** [comment]
I wonder if it is possible to optimize the image size for each enviroment.

We have shop 72G, shop admin 9G, reddit 50G, gitlab 72G, wikipedia 89G here.
