### ISSUE TITLE
Unable to access website 

### ISSUE THREAD

**Issue by MurtyShikhar** [web-arena-x/webarena#154]
Hi, 
Firstly thank you so much for the dataset! I've been following the instructions on creating a custom EC2 instance. I think i followed them exactly to the dot, but unfortunately, i'm unable to access the website from outside the EC2 instance. 

I suspect this has to do with my security group settings. Here is what I have as my "inbound rules":[
<img width="1406" alt="Screenshot 2024-07-05 at 12 21 29 PM" src="https://github.com/web-arena-x/webarena/assets/11057713/822dfef2-016e-440e-974f-02a8bf992c6f">
](url)

I know the website is up because running `curl -L localhost:7770` gives me the contents of the shopping website, but this exact command (with localhost replaced with the elastic IP of the instance) does not work from my personal laptop. Is there something I'm missing?

[For even more context, i'm using the t3a.xlarge machines with the provided AMI image]

Thanks!

**Comment by frankxu2004** [comment]
For inbound rule select TCP as protocol, and allow all port from all sources. Currently your ports opened are not exactly the websites ports such as 7780
