### ISSUE TITLE
Bug in the interaction between the environment and the action?

### ISSUE THREAD

**Issue by njucckevin** [web-arena-x/webarena#16]
I tried the minimal_example.py with some other actions, but the interaction seems strange. For example, for the task `156.json`, the first action I choose is `[xxx] link 'Starred 7'` by `click [xxx]`, this first step is ok in the chrome ui; the second action I choose is `[yyyy] link 'Explore'` by `click [yyyy]`, but this step doesn't seem to worked in the ui; after that, I action again by `click [yyyy]` and this time it work well and bring me to the 'Explore' page.
I noticed that when the `actree_obs` head with `Tab {idx}`, there maybe some problem with the next action. But different action seems have different behavior, some work and others not.
This interaction confuse me a lot.

**Comment by njucckevin** [comment]
It seems that in some case the obs["text"] show the whole page (including scroll up and down), instead of the current page.
For example, click `link 'The A11Y Project / a11yproject.coma11yproject.contributor.me'` in `156.json`.

**Comment by njucckevin** [comment]
The first problem magically disappeared when I got home, everything was fine even at sleep=1.5. I will check it tomorrow in my office. (⊙ｏ⊙)

**Comment by njucckevin** [comment]
The first problem seems to be related to the network environment.
1. Using my own wifi, problem exist;
2. Using my own wifi+vpn, work well;
3. Using my office wifi or (+vpn), problem exist;
Notice that my office wifi seems have it own vpn.

**Comment by shuyanzhou** [comment]
Thanks for the analysis!
