### ISSUE TITLE
goto http://homepage.com/password.html action does not work

### ISSUE THREAD

**Issue by MurtyShikhar** [web-arena-x/webarena#166]
Hello!

I've setup my own AWS instance for hosting webarena. However, the following action results in a "500 Internal Server Error":
`goto http://homepage.com/password.html`.

Upon looking at the files more closely, I don't see password.html inside `environment_docker/webarena-homepage/templates`. Is this a missing file? (I guess not being able to view passwords is not a dealbreaker if test time instructions all come with a cookie file for auto-login, but definitely makes unsupervised browsing in the environment limited).

Thanks!!

**Comment by shuyanzhou** [comment]
Hi @MurtyShikhar The password is a legacy page because back to then the auto login was a bit buggy. Your understanding is correct, it is not a dealbreaker right now. 

> but definitely makes unsupervised browsing in the environment limited

I did not quite understand this though, can you elaborate?

**Comment by MurtyShikhar** [comment]
Thanks Shuyan, this makes perfect sense! 

I guess the bit about unsupervised browsing doesn't make much sense without added context, but in a nutshell, the original action space had an action for going to the passwords page and a model could use that and get confused because it returns a 404. I'll just remove it! :-)
