### ISSUE TITLE
could not download the google drive document of the website

### ISSUE THREAD

**Issue by HU-xiaobai** [web-arena-x/webarena#17]
<img width="550" alt="1692791007175" src="https://github.com/web-arena-x/webarena/assets/85933274/ef4e235d-57e4-4733-a076-bfbba84c8516">

hi could you help me with that? I could not download the google drive document of website. anyone could download the document now?

**Comment by neubig** [comment]
I was able to download it now, but we'll try to create a mirror as well and post it on the site. Thanks for notifying us of the problem!

**Comment by Andrewzh112** [comment]
great work! i was wondering the dataset can be hosted on huggingface if possible

**Comment by shuyanzhou** [comment]
@Andrewzh112 Good point, I will upload it to HF ASAP

**Comment by Andrewzh112** [comment]
> @Andrewzh112 Good point, I will upload it to HF ASAP

thanks! let us know when the links are up

**Comment by shuyanzhou** [comment]
@HU-xiaobai checkout the mirror sites we provide in the [README file](https://github.com/web-arena-x/webarena/tree/main/environment_docker)
