### ISSUE TITLE
Openstreet map docker image

### ISSUE THREAD

**Issue by llv22** [web-arena-x/webarena#175]
Hi, can I use https://github.com/openstreetmap/openstreetmap-website/blob/master/DOCKER.md to setup docker of openstreetmap? Could you clarify?

**Comment by llv22** [comment]
finished configuration, succeed.

**Comment by AuroraLHL** [comment]
hi,I met the same question,could you please tell me how to setup docker of oepnstreetmap,thank you!

**Comment by ruhanaazam** [comment]
Same question here. Can we follow the docker set up from OSM's directory?

**Comment by llv22** [comment]
@ruhanaazam I followed it to set up my OSM, no issue and already finished my agent framework

**Comment by llv22** [comment]
> hi,I met the same question,could you please tell me how to setup docker of oepnstreetmap,thank you!

Please check the reference I mentioned in the ticket, which will be enough for such setup

**Comment by lrel7** [comment]
@llv22 Hi, thank you very much for the information! I noticed that in the "Loading an OSM extract" section of the instruction you provided, it mentions that the installation does not come with any geographic data preloaded. Have you manually loaded any OSM extracts yourself?

**Comment by llv22** [comment]
@lrel7 here is the bash script for importing north America data. you can also try with others

1. Download [OpenStreetMap Data Extracts](https://download.geofabrik.de/):

```bash
wget https://download.geofabrik.de/north-america-latest.osm.pbf
```
2. Import
```bash
docker compose run --rm web osmosis \
    -verbose    \
    --read-pbf north-america-latest.osm.pbf \
    --log-progress \
    --write-apidb \
        host="db" \
        database="openstreetmap" \
        user="openstreetmap" \
        validateSchemaVersion="no"
```

**Comment by ruhanaazam** [comment]
@llv22 Is the north american data sufficient for all the web arena test cases? Do you know?

**Comment by llv22** [comment]
@ruhanaazam please check your cases. I have extended the test cases

**Comment by lrel7** [comment]
@llv22 Thank you very much! But do you remember approximately how long it took to import the data? I'm currently importing the North America data, but it has been a day and still not finished. I'm wondering if this is expected.

**Comment by lrel7** [comment]
@llv22 Thanks again! I understand now

**Comment by newlearnt** [comment]
For WebArena evaluation, how do I create map using Docker, or what data should I import？

**Comment by newlearnt** [comment]
@ruhanaazam For WebArena evaluation, how can I create map using Docker, or what data should I import？do you know？
