### ISSUE TITLE
Some links point to an external site

### ISSUE THREAD

**Issue by kohjingyu** [web-arena-x/webarena#18]
Hi,

I've set up the shopping environment locally according to the [instructions here](https://github.com/web-arena-x/webarena/blob/main/environment_docker/README.md#shopping-website-onestopshop). I've set my shopping url to http://localhost:7770.

Most of it seems to work, but some of the links point to an external site, rather than localhost. For example:
<img width="1719" alt="Screen Shot 2023-08-23 at 11 08 27 AM" src="https://github.com/web-arena-x/webarena/assets/2196979/b8d2c60c-05d8-4a90-9734-2d0c5e32ddc1">

The links that seem to be affected are:

- http://metis.lti.cs.cmu.edu:7770/customer/account/
- http://metis.lti.cs.cmu.edu:7770/wishlist/
- http://metis.lti.cs.cmu.edu:7770/customer/account/login/
- http://metis.lti.cs.cmu.edu:7770/customer/account/create/
- http://metis.lti.cs.cmu.edu:7770/checkout/cart/
- http://metis.lti.cs.cmu.edu:7770/sales/guest/form/
- http://metis.lti.cs.cmu.edu:7770/contact/

Perhaps I missed a variable to be set, or it's something related to login?

Thanks!

**Comment by shuyanzhou** [comment]
Thanks for reporting this. We looked into it a bit, but still couldn't locate the exact problem, it *might* come from the cache. Can you run the following commands to fully flush the cache and see if it works

```bash
docker exec shopping /var/www/magento2/bin/magento indexer:reset
docker exec shopping /var/www/magento2/bin/magento indexer:reindex
docker exec shopping /var/www/magento2/bin/magento cache:clean
```

**Comment by nicholaschenai** [comment]
> Thanks for reporting this. We looked into it a bit, but still couldn't locate the exact problem, it _might_ come from the cache. Can you run the following commands to fully flush the cache and see if it works
> 
> ```shell
> docker exec shopping /var/www/magento2/bin/magento indexer:reset
> docker exec shopping /var/www/magento2/bin/magento indexer:reindex
> docker exec shopping /var/www/magento2/bin/magento cache:clean
> ```

I managed to replicate this problem to a larger degree: after entering localhost:7770, I got redirected to the metis version.

Following the instructions to clear cache doesnt work

**Comment by shuyanzhou** [comment]
@frankxu2004 let's try to reproduce it in our server

**Comment by shuyanzhou** [comment]
Thanks @kohjingyu @nicholaschenai for reporting the problem. We were able to locate the problem finally. Please re-open if the fix doesn't work

**Comment by kohjingyu** [comment]
Thanks for the fix. The URL redirect issue (which I experienced once earlier) seems to be fixed, but these links:

```
http://metis.lti.cs.cmu.edu:7770/customer/account/
http://metis.lti.cs.cmu.edu:7770/wishlist/
http://metis.lti.cs.cmu.edu:7770/customer/account/login/
http://metis.lti.cs.cmu.edu:7770/customer/account/create/
http://metis.lti.cs.cmu.edu:7770/checkout/cart/
http://metis.lti.cs.cmu.edu:7770/sales/guest/form/
http://metis.lti.cs.cmu.edu:7770/contact/
```

still point to metis rather than localhost. Perhaps there is some other Magneto url that needs to be set?
