### ISSUE TITLE
Instructions to setup env homepage needs updating. Links in env homepage wrong

### ISSUE THREAD

**Issue by nicholaschenai** [web-arena-x/webarena#23]
1. In the homepage section in https://github.com/web-arena-x/webarena/tree/main/environment_docker the instructions mention to change <your-server-hostname> in webarena_homepage/index.html which does not link correctly. It should be webarena-homepage/templates/index.html

2. When running the env homepage, some links are wrong. The entire top row links to <location homepage is hosted>:4399/<your-server-hostname>:<port>/etc when it should be <your-server-hostname>:<port>/etc. Wikipedia links to the metis version instead of self hosted version. Documentation links to live sites (not sure if this is intended, but I thought the whole point of webarena is to have a reproducible env instead of live sites)

**Comment by shuyanzhou** [comment]
Thanks for pointing them out @nicholaschenai. Would you kindly submit a PR to fixes the issues?

> Documentation links to live sites

We are still working on dockerizing the documentation sites. As they are read-only sites and they don't change rapidly, I think it is safe to use it for test purpose rn.
