### ISSUE TITLE
Issue on gitlab evaluation

### ISSUE THREAD

**Issue by ltzheng** [web-arena-x/webarena#24]
When the task is to create a new project from the JEKYLL template in gitlab, the evaluation is based on the project's initial commit message "Initialized from 'JEKYLL' project template". However, this is different from the initial commit log for projects created using template Pages/Jekyll. This also happens for the HTML template.

Thanks!

**Comment by shuyanzhou** [comment]
Thanks! Great catch. I am creating an issue #25  to gather all such errors and we will try to fix all known issues as soon as possible. We will properly acknowledge any contributions to reporting/fixing such bugs in the repo's REAME file in the future.
