### ISSUE TITLE
Edit: no issue

### ISSUE THREAD

**Issue by nicholaschenai** [web-arena-x/webarena#26]
The prompts use 'homepage.com' but there doesnt seem to be any functions to substitute that with the user defined homepage

**Comment by shuyanzhou** [comment]
If the `HOMEPAGE` constant is configured correctly, the agent should be able to visit the homepage through `goto [http://homepage.com]`. The code is [here](https://github.com/web-arena-x/webarena/blob/main/agent/prompts/prompt_constructor.py#L107)

The goal of having this homepage is to help the agent to perform cross-website tasks

**Comment by nicholaschenai** [comment]
thanks for clarifying!
