### ISSUE TITLE
Support for HF models 

### ISSUE THREAD

**Issue by karthik19967829** [web-arena-x/webarena#27]
Hi, do we support huggingface models?
If any internal internal tests were done with llama and the insights can be shared that will be great

**Comment by lihkinVerma** [comment]
There is hugging face model support in the code. But I am not sure, if they tested with LLaMa or other HF models, as the paper do not share those results in any appendix.

**Comment by frankxu2004** [comment]
one way to support this is to use vllm to set up an inference endpoint, and then server the OSS model like LLAMA with it, and use that new OpenAI-compatible endpoint.
