### ISSUE TITLE
Can you share some failure cases?

### ISSUE THREAD

**Issue by Leolty** [web-arena-x/webarena#3]
Hi! 

Thank you very much for your work. It's awesome! I was wondering if you could share more failure cases besides the few one shared in the paper?

Thanks,
Tianyang

**Comment by Leolty** [comment]
BTW, here is a little typo :).

<img width="930" alt="Screenshot 2023-08-01 at 8 55 24 PM" src="https://github.com/web-arena-x/webarena/assets/58247268/b4c861f4-da56-4d7d-8088-4f1d76a3d724">

**Comment by shuyanzhou** [comment]
Hi @Leolty, absolutely! We have all trajectories recorded. Let me clean them and upload them by the end of this week. And thanks for catching the typo, we will update in the next version :)

**Comment by shuyanzhou** [comment]
Hey @Leolty, check out the resources we just uploaded
