### ISSUE TITLE
Adding option to clear text

### ISSUE THREAD

**Issue by RichardZhu123** [web-arena-x/webarena#33]
I believe currently there is only a function to ```type[]```. However, if there is already text in the field, there is no way to clear the text.

Is it possible to add a ```clear[]``` function?

**Comment by shuyanzhou** [comment]
It is possible to add another action; however, this would also grow the action space. 

The ways to delete the existing content in an input box are
* `press [meta+a]` to select all, then `press [backspace]`
* `press [backspace]` for `k` times until empty.

**Comment by shuyanzhou** [comment]
Check out #36 for an example
