### ISSUE TITLE
Build a tree over the pages in the website

### ISSUE THREAD

**Issue by Andrewzh112** [web-arena-x/webarena#34]
Hi,

I wonder if the authors have any ideas or hint on how to quickly build a tree/graph over all the pages in the environment where the edges are the links that link the two pages.

Thanks,
Andrew

**Comment by shuyanzhou** [comment]
Can you provide an example? I guess the way is to parse the HTML/Accessibility tree to extract the URLs and build the graphs on our own.

**Comment by Andrewzh112** [comment]
will try, thanks for the headsup
