### ISSUE TITLE
Playground Wrongness

### ISSUE THREAD

**Issue by fengsxy** [web-arena-x/webarena#4]
<img width="1057" alt="image" src="https://github.com/web-arena-x/webarena/assets/57928993/a52b861e-1ba8-42cc-872b-2e11b7d6bdce">
I have follow the instructions, and after I run "python minimal_example.py" I have meet this problems.

**Comment by shuyanzhou** [comment]
It looks like you are running Playwright in a headless server that does not have a `DISPLAY` variable. Can you try to set `headless=True` [here](https://github.com/web-arena-x/webarena/blob/main/minimal_example.py#L71)?

**Comment by ScottLinnn** [comment]
I'm running `auto_login.py`
If I run `headless=True`, I will get:

```
playwright._impl._api_types.Error: net::ERR_ABORTED at ec2-xxxxxxxxxxus-east-2.compute.amazonaws.com:9999/user/MarvelsGrantMan136/account
=========================== logs ===========================
navigating to "ec2-xxxxxxxxxx.us-east-2.compute.amazonaws.com:9999/user/MarvelsGrantMan136/account", waiting until "load"
```

If I run  `headless=False`, I will get the error as OP.

It's a lot of frustration trying to get the evaluation running...
