### ISSUE TITLE
one_stop_market login

### ISSUE THREAD

**Issue by zhilizju** [web-arena-x/webarena#45]
Nice work ! "one_stop_market" URL: http://metis.lti.cs.cmu.edu:7770/ seems to have some issues: I can't log in using the password from https://github.com/web-arena-x/webarena/blob/main/browser_env/env_config.py, the other environments are working fine.

**Comment by shuyanzhou** [comment]
* The demo site is supposed to be http://ec2-3-131-244-37.us-east-2.compute.amazonaws.com:7770/ 
* Can you try to login in incognito mode?

**Comment by zhilizju** [comment]
Thank you for your prompt response ! The issue has been resolved.
