### ISSUE TITLE
Reproducibility of Webarena under high temperature

### ISSUE THREAD

**Issue by zwhe99** [web-arena-x/webarena#48]
Thank you for your amazing work @shuyanzhou ! I notice that you set the temperature to 1.0. Will this make it difficult to reproduce the results?

**Comment by foreverpiano** [comment]
run for 10 times and choose the best as result XD

**Comment by shuyanzhou** [comment]
@zwhe99 This is a good point. We will report the number with temperature `0` on at least one model in the coming month.

**Comment by shuyanzhou** [comment]
As promised, we have added an experiment with `t=0` and the results are in Table 5 in our [updated version](https://arxiv.org/pdf/2307.13854.pdf)
<img width="544" alt="image" src="https://github.com/web-arena-x/webarena/assets/29911200/fcca7e60-2207-453d-9eca-a1bf62898e8d">
