### ISSUE TITLE
task 615-619 labels have "locator" in format that raises error

### ISSUE THREAD

**Issue by nicholaschenai** [web-arena-x/webarena#53]
task 615-619 labels: all of them have

"locator": "[...document.querySelector('.submission__inner').querySelectorAll('[href],[src]')].map(elem => elem.getAttribute('href') || elem.getAttribute('src')).join(' ')",
          
however, in webarena/evaluation_harness/evaluators.py class HTMLContentExactEvaluator(Evaluator) line 236 on, locators are expected to be empty or startswith "document." or "func.". Hence, ValueError is raised for 615-619

**Comment by shuyanzhou** [comment]
Good catch! #54 has fixed it!
