### ISSUE TITLE
AssertionError: Cookie ./.auth/gitlab_state.json expired.

### ISSUE THREAD

**Issue by Yangyi-Chen** [web-arena-x/webarena#64]
Hi Thanks for your great work! 

I've followed the instructions to set up the docker environments. But when I run this file: python browser_env/auto_login.py . It continually yields this Assertion error: AssertionError: Cookie ./.auth/gitlab_state.json expired. 

I checked and found that only this cookie file expires. Could you help me to look into this problem? Many thanks!

**Comment by shuyanzhou** [comment]
Hi @Yangyi-Chen, unfortunately, I wasn't able to reproduce the error from my end. Are you still facing this error? If so, can you check if you could login via http://ec2-3-131-244-37.us-east-2.compute.amazonaws.com:8023/explore?

**Comment by Yangyi-Chen** [comment]
Thanks for your quick response. The amazing thing is I do not have this error when I rerun the same code. so i close this issue.

**Comment by operator22th** [comment]
I'm facing the same problem. Any thoughts on how to fix it? Have tried several times.

**Comment by lhyscau** [comment]
I meet the same error. Firstly, check the username and passwowd can successfully used to login the corresponding website. If not succeed, your container may be have some bug. So I advise to reconstruct your container when you ensure your image is right.
