### ISSUE TITLE
A probability that the execution will fail? 

### ISSUE THREAD

**Issue by Yangyi-Chen** [web-arena-x/webarena#65]
Thanks for the great work! 

I'm wondering whether there is a probability that the execution of taking actions can fail in the environment. 

For example, I'm playing with the shopping_admin environment. In the first step, I perform the click action in a certain element: create_id_based_action(f"click [877]"). 

Sometimes it works and navigates to a new page, but sometimes it doesn't. So is this a common issue in the environment, or maybe just errors on my side? Thanks!

**Comment by shuyanzhou** [comment]
Could you recall what is the element of 877? Perhaps it is due to not wait long enough and the new page is not loaded yet?

**Comment by Yangyi-Chen** [comment]
oh i see. That could be a reason. 

I also find that a potential reason is the element ID is not fixed when I load the same web page. Is this can happen sometimes in the environment? Thanks!

**Comment by shuyanzhou** [comment]
> I also find that a potential reason is the element ID for the same web component (like a button) is not fixed when I load the same web page. Is this can happen sometimes in the environment? Thanks!

This is expected. The ID is generated randomly every time.

**Comment by Yangyi-Chen** [comment]
I see. Thanks for your responses!
