### ISSUE TITLE
Is it possible to seperate data and env dependencies in docker images? The images are too big now. 

### ISSUE THREAD

**Issue by Junpliu** [web-arena-x/webarena#69]
Is it possible to release data and env/dependencies separately, where only env/dependencies are included in the images?

**Comment by shuyanzhou** [comment]
Thanks for the question. I understand that the size of the images is quite large. Unfortunately, separating the data from the environment is non-trivial as it requires (1) setting up fresh websites and (2) import data. There can be a lot issues happening during both steps.
