### ISSUE TITLE
 Issue with Accessibility Tree Missing Information

### ISSUE THREAD

**Issue by jingrsu** [web-arena-x/webarena#70]
After executing the evaluation script using the following command:
```
python run.py \
  --instruction_path agent/prompts/jsons/p_cot_id_actree_2s.json \ # this is the reasoning agent prompt we used in the paper
  --test_start_idx 0 \
  --test_end_idx 100 \
  --model gpt-3.5-turbo \
  --result_dir output
```
I've observed discrepancies in the Accessibility Tree generated for certain HTML logs. Specifically, some elements present in the web page are missing in the Accessibility Tree.
# Example Case:
An instance of this issue is evident in the output for `render_23.html`. The URL for this HTML log is: http://<shopping_site_domain>:7770/3-pack-samsung-galaxy-s6-screen-protector-nearpow-tempered-glass-screen-protector-with-9h-hardness-crystal-clear-easy-bubble-free-installation-scratch-resist.html
In the html log `render_23.html`, as seen in the screenshot below,  the content of T. Grannon's review is missing in the Accessibility Tree, though the title of this review is present.  Additionally, the title of the subsequent review appears.
<img width="1451" alt="截屏2023-12-04 下午1 27 08" src="https://github.com/web-arena-x/webarena/assets/21058087/c222a6af-3e70-434a-91c9-b5d433ce0777">
The actual result shows a missing entry for T. Grannon's review in the Accessibility Tree.

**Comment by shuyanzhou** [comment]
Thanks for the report, this is related to a bug in cleaning the AXTree.
