### ISSUE TITLE
Will the trace of human annotation process be released? 

### ISSUE THREAD

**Issue by Junpliu** [web-arena-x/webarena#73]
Thanks for the great research! 

The traces of models are pretty useful for me, and I wonder whether the trace of the human annotation process, i.e., 810 test configs, will be released.

**Comment by shuyanzhou** [comment]
Hi, we have ~170 trajectories available in the form of playwright traces. I will release them soon. Note that the recorded trajectories are pretty noisy and may require efforts to clean them up.

**Comment by wookayin** [comment]
Thanks for posting the human trajectories https://drive.google.com/drive/folders/1NrN_sawtYK2V_uHnmmS8ugmGIKUAsPgt, but all the data here is given in a very *raw*, internal format, and not quite human-readable, so they are hardly useful. I tried to convert them into some *useful* data (i.e. like into action sequences or some "trajectory" data), but it's quite difficult to process the traces.

Do you have any advice here or would you be willing to provide some "processed" data that you might already have used as a part of experiments?
