### ISSUE TITLE
Error with the test run

### ISSUE THREAD

**Issue by Anticope12** [web-arena-x/webarena#8]
Hello team,

Fantastic tool, I'm trying to replicate the tests examples. 

The majority of the tests have the following error, Any suggestions? 

The previous prediction you issued was "Let's think step-by-step. This page shows a list of links and buttons. There is a search box with the label 'Search query'. I will click on the search box to type the query. So the action I will perform is "click [60]".". However, the format was incorrect. Ensure that the action is wrapped inside a pair of ``` and enclose arguments within [] as follows: ```action [arg] ...```.
{'action_type': , 'coords': array([0., 0.], dtype=float32), 'element_role': 0, 'element_name': '', 'text': [], 'page_number': 0, 'url': '', 'nth': 0, 'pw_code': '', 'element_id': '', 'key_comb': '', 'direction': '', 'answer': 'Early stop: Failed to parse actions for 3 times', 'raw_prediction': ''}

All the tests/task has the same output from openai_utils.py 
    answer = "Let's think step-by-step. This page shows a list of links and buttons. There is a search box with the label 'Search query'. I will click on the search box to type the query. So the action I will perform is \"click [60]\"."

**Comment by shuyanzhou** [comment]
Hi, are you using the same prompt as we [did](https://github.com/web-arena-x/webarena/blob/main/agent/prompts/raw/p_cot_id_actree_2s.py) or did you write your own? 

The error you experience comes from the parsing failures. As you can see [here](https://github.com/web-arena-x/webarena/blob/main/agent/prompts/prompt_constructor.py#L233), we use a pair of ``` as the sign for the action prediction. It seems you the answer you generated used a pair of quotes (`"`) hence the parsing failed.

**Comment by Anticope12** [comment]
Hi @shuyanzhou ,
That's what I did run 
 export OPENAI_API_KEY=KEY
python run.py --test_start_idx 156 --test_end_idx 157 --model gpt-3.5-turbo --result_dir /PATH/your_result_dir

Haven't done any changes to the code.

However, if I trigger [code](https://github.com/web-arena-x/webarena/blob/main/minimal_example.py)
Directly it's running without any issues. Any thoughts?

**Comment by Anticope12** [comment]
Here is the render_html: 
First attempt: Action None. 

`<div class='prev_action' style='background-color:pink'>None</div>
<div class='predict_action'><div class='raw_parsed_prediction' style='background-color:grey'><pre>Let's think step-by-step. This page shows a list of links and buttons. There is a search box with the label 'Search query'. I will click on the search box to type the query. So the action I will perform is "click [60]".</pre></div><div class='action_object' style='background-color:grey'><pre>{'action_type': <ActionTypes.NONE: 0>, 'coords': array([0., 0.], dtype=float32), 'element_role': 0, 'element_name': '', 'text': [], 'page_number': 0, 'url': '', 'nth': 0, 'pw_code': '', 'element_id': '', 'key_comb': '', 'direction': '', 'answer': '', 'raw_prediction': 'Let\'s think step-by-step. This page shows a list of links and buttons. There is a search box with the label \'Search query\'. I will click on the search box to type the query. So the action I will perform is "click [60]".'}</pre></div><div class='parsed_action' style='background-color:yellow'><pre>none</pre></div></div>`


2nd:
<div class='predict_action'><div class='raw_parsed_prediction' style='background-color:grey'><pre>Let's think step-by-step. This page shows a list of links and buttons. There is a search box with the label 'Search query'. I will click on the search box to type the query. So the action I will perform is "click [60]".</pre></div><div class='action_object' style='background-color:grey'><pre>{'action_type': <ActionTypes.NONE: 0>, 'coords': array([0., 0.], dtype=float32), 'element_role': 0, 'element_name': '', 'text': [], 'page_number': 0, 'url': '', 'nth': 0, 'pw_code': '', 'element_id': '', 'key_comb': '', 'direction': '', 'answer': '', 'raw_prediction': 'Let\'s think step-by-step. This page shows a list of links and buttons. There is a search box with the label \'Search query\'. I will click on the search box to type the query. So the action I will perform is "click [60]".'}</pre></div><div class='parsed_action' style='background-color:yellow'><pre>none</pre></div></div>

the last:
`<div class='predict_action'><div class='raw_parsed_prediction' style='background-color:grey'><pre>Let's think step-by-step. This page shows a list of links and buttons. There is a search box with the label 'Search query'. I will click on the search box to type the query. So the action I will perform is "click [60]".</pre></div><div class='action_object' style='background-color:grey'><pre>{'action_type': <ActionTypes.NONE: 0>, 'coords': array([0., 0.], dtype=float32), 'element_role': 0, 'element_name': '', 'text': [], 'page_number': 0, 'url': '', 'nth': 0, 'pw_code': '', 'element_id': '', 'key_comb': '', 'direction': '', 'answer': '', 'raw_prediction': 'Let\'s think step-by-step. This page shows a list of links and buttons. There is a search box with the label \'Search query\'. I will click on the search box to type the query. So the action I will perform is "click [60]".'}</pre></div><div class='parsed_action' style='background-color:yellow'><pre>none</pre></div></div>`

**Comment by shuyanzhou** [comment]
I spot some strange inconsistency -- it seems like you are using the `direct` prompt which is supposed to generate the action *without* any reasoning step. However, the generation you listed does have reasoning steps. Can you check if the prompts in `agent/prompts/jsons/p_direct_id_actree_2s.json` is the same as the one defined in `agent/prompts/raw/p_direct_id_actree_2s.py`?

**Comment by Anticope12** [comment]
after the new updates you added to the code yesterday, it's working. 
Thank you for the fix.
