### ISSUE TITLE
OneStopMarket customer login not working on Amazon Image

### ISSUE THREAD

**Issue by Miking98** [web-arena-x/webarena#84]
Hi, 

For some reason the Customer login is not working on the Amazon machine instance. Example here: [http://ec2-13-59-140-179.us-east-2.compute.amazonaws.com:7770/customer/account/login/](http://ec2-13-59-140-179.us-east-2.compute.amazonaws.com:7770/customer/account/login/). 

I ran all the docker commands, so please let me know if there's a simple way to debug this / what might be going on. Thanks!

**Comment by shuyanzhou** [comment]
Hi, I tried your instance and could log in with the default username and password. Can you try to login with incognito mode? We noticed that under the non-incognito setting, the shopping site's cookie seems to conflict with that of reddit.

**Comment by Miking98** [comment]
Ah yep thanks, that fixed it!

**Comment by wy9815** [comment]
What is the default username and password then? I didn't see them in any readme files

**Comment by shuyanzhou** [comment]
@wy9815 they are [here](https://github.com/web-arena-x/webarena/blob/main/browser_env/env_config.py#L32)
