### ISSUE TITLE
wikipedia url 

### ISSUE THREAD

**Issue by Quester-one** [web-arena-x/webarena#85]
It's a very interesting job, but I have a small question. When I access the URL of WIKIPEDIA, I can't open it from the browser. Is there something I haven't configured？

**Comment by Quester-one** [comment]
http://ec2-3-131-244-37.us-east-2.compute.amazonaws.com:8888/wikipedia_en_all_maxi_2022-05/A/User:The_other_Kiwix_guy/Landing

**Comment by frankxu2004** [comment]
Sorry for the late reply. This URL is hosted on our demo server and it went down for a bit. It should work now. If you want the most stable experience, you could try follow our instructions in setting up your own AWS machine, or use our docker images to start up the website suites. Thanks!
