### ISSUE TITLE
how to efficiently reset changes to the environment?

### ISSUE THREAD

**Issue by lyneyandlynette** [web-arena-x/webarena#88]
It seems that for actions like posting a new submission on reddit will make the submission stay on the page and won't automatically delete itself. This is not very convenient for testing... Is there any way to efficiently undo all changed to the environment? Thank you!

**Comment by shuyanzhou** [comment]
Hi @lyneyandlynette, thanks, this is a good question. The recommended way is resetting the environment after each round of evaluation. 

```bash
# stop the dockers
docker stop shopping_admin forum gitlab shopping
# remove the docker images
docker remove shopping_admin forum gitlab shopping;
```
Depending on whether you are using the AMI or individual dockers, restart the dockers with the instructions in the [README](https://github.com/web-arena-x/webarena/blob/main/environment_docker/README.md) file. Let me know if you encounter any issues
