### ISSUE TITLE
Optimal trajectory data

### ISSUE THREAD

**Issue by shenao-zhang** [web-arena-x/webarena#9]
Hi,

Thanks for your excellent work and contribution! Since I was trying to generate some more examples as prompt, may I know if you have the optimal trajectories that lead to the reference answers in the dataset? If not, is there a way to record the trajectory while interacting in the web using keyboard and mouse?

Best,
Shenao

**Comment by shuyanzhou** [comment]
Aha, I guess I misunderstood the questions before

> if you have the optimal trajectories that lead to the reference answers in the dataset?

We didn't collect reference trajectories for the test data.

> Is there a way to record the trajectory while interacting in the web using keyboard and mouse

I have a semi-cooked tool to record the [playwright](https://playwright.dev/python/docs/codegen) action sequences specifically for the websites in WebArena. Extra efforts will be needed to convert the playwright element selections to concrete HTML/accessibility tree elements. I could release it soon if it sounds helpful to you.

**Comment by shenao-zhang** [comment]
That will be great! Closing the issue for now.
