### ISSUE TITLE
Run in Parallel

### ISSUE THREAD

**Issue by 594zyc** [web-arena-x/webarena#91]
Is there a way to spawn multiple environments and run them in parallel?

**Comment by shuyanzhou** [comment]
Not sure what exactly the context is, but if you are trying to speed up the evaluation, you can check the parallel eval script [here](https://github.com/web-arena-x/webarena/blob/main/parallel_run.sh)

**Comment by 594zyc** [comment]
Yes, this is exactly what I am looking for. Thanks!
