### ISSUE TITLE
Accessing the demo environment

### ISSUE THREAD

**Issue by oriyor** [web-arena-x/webarena#93]
Hi!

Thx for releasing the code and demo environment for this work! 

I am trying to access the demo environment using the links (https://webarena.dev/) or the minimal_example.py script and they don't seem to work, is it possible that the sites are not accessible or am I doing something wrong?

Thx again!
Ori

**Comment by shuyanzhou** [comment]
Hey, https://webarena.dev/ is the project page and the demo sites are here: https://webarena.dev/#try-it-yourself

**Comment by oriyor** [comment]
Thank you, it works now!
