### ISSUE TITLE
Security Vulnerability: PHP Version out of date

### ISSUE THREAD

**Issue by dragon18456** [web-arena-x/webarena#96]
The Docker image for the Reddit environment: postmill-populated-exposed-withimg.tar is built using php 8.1.17, which has a number of known security vulnerabilities: https://www.tenable.com/plugins/nessus/179317

Could you update the image to use php 8.1.22?

**Comment by shuyanzhou** [comment]
cc @frankxu2004 My understanding is that since these are not real websites, it is OK to keep the current version. Let us know your thoughts

**Comment by dragon18456** [comment]
I am trying to run this on docker locally and the network admin won't let me run this with an outdated version of PHP
